const app = require("./app");

const server = app.listen(4000, () => {
    console.log(`Server is running at http://localhost:4000`);
});


// {
//     config: {
//       transitional: {
//         silentJSONParsing: true,
//         forcedJSONParsing: true,
//         clarifyTimeoutError: false
//       },
//       adapter: [Function: httpAdapter],
//       transformRequest: [ [Function: transformRequest] ],
//       transformResponse: [ [Function: transformResponse] ],
//       timeout: 0,
//       xsrfCookieName: 'XSRF-TOKEN',
//       xsrfHeaderName: 'X-XSRF-TOKEN',
//       maxContentLength: -1,
//       maxBodyLength: -1,
//       validateStatus: [Function: validateStatus],
//       headers: {
//         Accept: 'application/json',
//         'Content-Type': 'application/json',
//         authorization: 'Basic cmFuZG9tc3RyaW5nOjY4NjEyZjc0MDM1OGM3YTU3MTAxMDJkNmNiYzE4MzNjLXVzMTQ=',
//         'User-Agent': 'axios/0.26.1',
//         'Content-Length': 98
//       },
//       method: 'post',
//       url: 'https://us14.api.mailchimp.com/3.0/lists/9736fa7dbe/members',  
//       data: '{"email_address":"mailchimp.repo@gmail.com","status":"subscribed","merge_fields":{"FNAME":"Duke"}}'
//     },
//     request: <ref *1> ClientRequest {
//       _events: [Object: null prototype] {
//         abort: [Function (anonymous)],
//         aborted: [Function (anonymous)],
//         connect: [Function (anonymous)],
//         error: [Function (anonymous)],
//         socket: [Function (anonymous)],
//         timeout: [Function (anonymous)],
//         prefinish: [Function: requestOnPrefinish]
//       },
//       _eventsCount: 7,
//       _maxListeners: undefined,
//       outputData: [],
//       outputSize: 0,
//       writable: true,
//       destroyed: false,
//       _last: true,
//       chunkedEncoding: false,
//       shouldKeepAlive: false,
//       maxRequestsOnConnectionReached: false,
//       _defaultKeepAlive: true,
//       useChunkedEncodingByDefault: true,
//       sendDate: false,
//       _removedConnection: false,
//       _removedContLen: false,
//       _removedTE: false,
//       _contentLength: null,
//       _hasBody: true,
//       _trailer: '',
//       finished: true,
//       _headerSent: true,
//       _closed: false,
//       socket: TLSSocket {
//         _tlsOptions: [Object],
//         _secureEstablished: true,
//         _securePending: false,
//         _newSessionPending: false,
//         _controlReleased: true,
//         secureConnecting: false,
//         _SNICallback: null,
//         servername: 'us14.api.mailchimp.com',
//         alpnProtocol: false,
//         authorized: true,
//         authorizationError: null,
//         encrypted: true,
//         _events: [Object: null prototype],
//         _eventsCount: 10,
//         connecting: false,
//         _hadError: false,
//         _parent: null,
//         _host: 'us14.api.mailchimp.com',
//         _readableState: [ReadableState],
//         _maxListeners: undefined,
//         _writableState: [WritableState],
//         allowHalfOpen: false,
//         _sockname: null,
//         _pendingData: null,
//         _pendingEncoding: '',
//         server: undefined,
//         _server: null,
//         ssl: [TLSWrap],
//         _requestCert: true,
//         _rejectUnauthorized: true,
//         parser: null,
//         _httpMessage: [Circular *1],
//         [Symbol(res)]: [TLSWrap],
//         [Symbol(verified)]: true,
//         [Symbol(pendingSession)]: null,
//         [Symbol(async_id_symbol)]: 20,
//         [Symbol(kHandle)]: [TLSWrap],
//         [Symbol(kSetNoDelay)]: false,
//         [Symbol(lastWriteQueueSize)]: 0,
//         [Symbol(timeout)]: null,
//         [Symbol(kBuffer)]: null,
//         [Symbol(kBufferCb)]: null,
//         [Symbol(kBufferGen)]: null,
//         [Symbol(kCapture)]: false,
//         [Symbol(kBytesRead)]: 0,
//         [Symbol(kBytesWritten)]: 0,
//         [Symbol(connect-options)]: [Object],
//         [Symbol(RequestTimeout)]: undefined
//       },
//       _header: 'POST /3.0/lists/9736fa7dbe/members HTTP/1.1\r\n' +
//         'Accept: application/json\r\n' +
//         'Content-Type: application/json\r\n' +
//         'authorization: Basic cmFuZG9tc3RyaW5nOjY4NjEyZjc0MDM1OGM3YTU3MTAxMDJkNmNiYzE4MzNjLXVzMTQ=\r\n' +
//         'User-Agent: axios/0.26.1\r\n' +
//         'Content-Length: 98\r\n' +
//         'Host: us14.api.mailchimp.com\r\n' +
//         'Connection: close\r\n' +
//         '\r\n',
//       _keepAliveTimeout: 0,
//       _onPendingData: [Function: nop],
//       agent: Agent {
//         _events: [Object: null prototype],
//         _eventsCount: 2,
//         _maxListeners: undefined,
//         defaultPort: 443,
//         protocol: 'https:',
//         options: [Object: null prototype],
//         requests: [Object: null prototype] {},
//         sockets: [Object: null prototype],
//         freeSockets: [Object: null prototype] {},
//         keepAliveMsecs: 1000,
//         keepAlive: false,
//         maxSockets: Infinity,
//         maxFreeSockets: 256,
//         scheduling: 'lifo',
//         maxTotalSockets: Infinity,
//         totalSocketCount: 1,
//         maxCachedSessions: 100,
//         _sessionCache: [Object],
//         [Symbol(kCapture)]: false
//       },
//       socketPath: undefined,
//       method: 'POST',
//       maxHeaderSize: undefined,
//       insecureHTTPParser: undefined,
//       path: '/3.0/lists/9736fa7dbe/members',
//       _ended: true,
//       res: IncomingMessage {
//         _readableState: [ReadableState],
//         _events: [Object: null prototype],
//         _eventsCount: 4,
//         _maxListeners: undefined,
//         socket: [TLSSocket],
//         httpVersionMajor: 1,
//         httpVersionMinor: 1,
//         httpVersion: '1.1',
//         complete: true,
//         rawHeaders: [Array],
//         rawTrailers: [],
//         aborted: false,
//         upgrade: false,
//         url: '',
//         method: null,
//         statusCode: 400,
//         statusMessage: 'Bad Request',
//         client: [TLSSocket],
//         _consuming: false,
//         _dumped: false,
//         req: [Circular *1],
//         responseUrl: 'https://us14.api.mailchimp.com/3.0/lists/9736fa7dbe/members',
//         redirects: [],
//         [Symbol(kCapture)]: false,
//         [Symbol(kHeaders)]: [Object],
//         [Symbol(kHeadersCount)]: 14,
//         [Symbol(kTrailers)]: null,
//         [Symbol(kTrailersCount)]: 0,
//         [Symbol(RequestTimeout)]: undefined
//       },
//       aborted: false,
//       timeoutCb: null,
//       upgradeOrConnect: false,
//       parser: null,
//       maxHeadersCount: null,
//       reusedSocket: false,
//       host: 'us14.api.mailchimp.com',
//       protocol: 'https:',
//       _redirectable: Writable {
//         _writableState: [WritableState],
//         _events: [Object: null prototype],
//         _eventsCount: 3,
//         _maxListeners: undefined,
//         _options: [Object],
//         _ended: true,
//         _ending: true,
//         _redirectCount: 0,
//         _redirects: [],
//         _requestBodyLength: 98,
//         _requestBodyBuffers: [],
//         _onNativeResponse: [Function (anonymous)],
//         _currentRequest: [Circular *1],
//         _currentUrl: 'https://us14.api.mailchimp.com/3.0/lists/9736fa7dbe/members',
//         [Symbol(kCapture)]: false
//       },
//       [Symbol(kCapture)]: false,
//       [Symbol(kNeedDrain)]: false,
//       [Symbol(corked)]: 0,
//       [Symbol(kOutHeaders)]: [Object: null prototype] {
//         accept: [Array],
//         'content-type': [Array],
//         authorization: [Array],
//         'user-agent': [Array],
//         'content-length': [Array],
//         host: [Array]
//       }
//     },
//     response: {
//       status: 400,
//       statusText: 'Bad Request',
//       headers: {
//         server: 'openresty',
//         'content-type': 'application/problem+json; charset=utf-8',
//         'content-length': '192',
//         'x-request-id': 'add399f6-8dcc-55ba-de29-db28177cb340',
//         link: '<https://us14.api.mailchimp.com/schema/3.0/Definitions/ProblemDetailDocument.json>; rel="describedBy"',
//         date: 'Tue, 19 Apr 2022 13:30:52 GMT',
//         connection: 'close'
//       },
//       config: {
//         transitional: [Object],
//         adapter: [Function: httpAdapter],
//         transformRequest: [Array],
//         transformResponse: [Array],
//         timeout: 0,
//         xsrfCookieName: 'XSRF-TOKEN',
//         xsrfHeaderName: 'X-XSRF-TOKEN',
//         maxContentLength: -1,
//         maxBodyLength: -1,
//         validateStatus: [Function: validateStatus],
//         headers: [Object],
//         method: 'post',
//         url: 'https://us14.api.mailchimp.com/3.0/lists/9736fa7dbe/members',      data: '{"email_address":"mailchimp.repo@gmail.com","status":"subscribed","merge_fields":{"FNAME":"Duke"}}'
//       },
//       request: <ref *1> ClientRequest {
//         _events: [Object: null prototype],
//         _eventsCount: 7,
//         _maxListeners: undefined,
//         outputData: [],
//         outputSize: 0,
//         writable: true,
//         destroyed: false,
//         _last: true,
//         chunkedEncoding: false,
//         shouldKeepAlive: false,
//         maxRequestsOnConnectionReached: false,
//         _defaultKeepAlive: true,
//         useChunkedEncodingByDefault: true,
//         sendDate: false,
//         _removedConnection: false,
//         _removedContLen: false,
//         _removedTE: false,
//         _contentLength: null,
//         _hasBody: true,
//         _trailer: '',
//         finished: true,
//         _headerSent: true,
//         _closed: false,
//         socket: [TLSSocket],
//         _header: 'POST /3.0/lists/9736fa7dbe/members HTTP/1.1\r\n' +       
//           'Accept: application/json\r\n' +
//           'Content-Type: application/json\r\n' +
//           'authorization: Basic cmFuZG9tc3RyaW5nOjY4NjEyZjc0MDM1OGM3YTU3MTAxMDJkNmNiYzE4MzNjLXVzMTQ=\r\n' +
//           'User-Agent: axios/0.26.1\r\n' +
//           'Content-Length: 98\r\n' +
//           'Host: us14.api.mailchimp.com\r\n' +
//           'Connection: close\r\n' +
//           '\r\n',
//         _keepAliveTimeout: 0,
//         _onPendingData: [Function: nop],
//         agent: [Agent],
//         socketPath: undefined,
//         method: 'POST',
//         maxHeaderSize: undefined,
//         insecureHTTPParser: undefined,
//         path: '/3.0/lists/9736fa7dbe/members',
//         _ended: true,
//         res: [IncomingMessage],
//         aborted: false,
//         timeoutCb: null,
//         upgradeOrConnect: false,
//         parser: null,
//         maxHeadersCount: null,
//         reusedSocket: false,
//         host: 'us14.api.mailchimp.com',
//         protocol: 'https:',
//         _redirectable: [Writable],
//         [Symbol(kCapture)]: false,
//         [Symbol(kNeedDrain)]: false,
//         [Symbol(corked)]: 0,
//         [Symbol(kOutHeaders)]: [Object: null prototype]
//       },
//       data: {
//         title: 'Member Exists',
//         status: 400,
//         detail: 'mailchimp.repo@gmail.com is already a list member. Use PUT to insert or update list members.',
//         instance: 'add399f6-8dcc-55ba-de29-db28177cb340'
//       }
//     },
//     isAxiosError: true,
//     toJSON: [Function: toJSON]